[package]
name = "attester"
version = "0.1.0"
edition = "2021"

[features]
itrustee-attester = ["base64-url", "rand"]
virtcca-attester = ["base64-url"]

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
rand = { workspace = true, optional = true }
base64-url = { workspace = true, optional = true }
async-trait.workspace = true
log.workspace = true
attestation-types.workspace = true
