[package]
name = "reference"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
base64.workspace = true
sled.workspace = true
openssl.workspace = true
hex.workspace = true
lazy_static.workspace = true
thiserror.workspace = true
