[workspace]
resolver = "2"
members = [
    "service",
    "verifier",
    "token"
]

[workspace.dependencies]
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0"
async-trait = "0.1.78"
cose-rust = "0.1.7"
ciborium = "0.2.2"
hex = "0.4"
openssl = "0.10.64"
log = "0.4.14"
futures = "0.3.30"
rand = "0.8.5"
ima-measurements = "0.2.0"
fallible-iterator = "0.2.0"

actix-web = "4.5"
env_logger = "0.9"
tokio = "1.0"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1.0"
base64-url = "3.0.0"
jsonwebtoken = "9.3.0"
clap = { version = "4.5.7", features = ["derive"] }

attester = {path = "../attestation-agent/attester"}
