[workspace]
resolver = "2"
members = [
    "service",
    "verifier",
    "token",
    "reference",
    "policy",
    "tests"
]

[workspace.dependencies]
anyhow = "1.0.80"
serde = "1.0"
serde_json = "1.0"
async-trait = "0.1.78"
cose-rust = "0.1.7"
ciborium = "0.2.2"
hex = "0.4"
openssl = "0.10.64"
log = "0.4.14"
futures = "0.3.30"
rand = "0.8.5"
ima-measurements = "0.2.0"
fallible-iterator = "0.2.0"

actix-web = "4.5"
env_logger = "0.9"
tokio = { version = "1", features = ["full"] }
strum = { version = "0.25", features = ["derive"] }
thiserror = "1.0"
base64-url = "3.0.0"
base64 = "0.22.0"
jsonwebtoken = "9.3.0"
clap = { version = "4.5.7", features = ["derive"] }
regorus = "0.2.2"
sled = "0.34.7"
lazy_static = "1.5.0"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
scc = "2.1"

attestation-types = {path = "../attestation-types"}
