[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
ciborium-ll.workspace = true
ciborium-io.workspace = true
ciborium.workspace = true
half.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
cose-rust.workspace = true
hex.workspace = true
openssl.workspace = true
log.workspace = true

attester.workspace = true

[dev-dependencies]

[features]
default = [ "itrustee-verifier","virtcca-verifier" ]
itrustee-verifier = []
virtcca-verifier = ["attester/virtcca-attester"]
