/* automatically generated by rust-bindgen 0.69.4 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct buffer_data {
    pub size: ::std::os::raw::c_uint,
    pub buf: *mut ::std::os::raw::c_uchar,
}
#[test]
fn bindgen_test_layout_buffer_data() {
    const UNINIT: ::std::mem::MaybeUninit<buffer_data> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<buffer_data>(),
        16usize,
        concat!("Size of: ", stringify!(buffer_data))
    );
    assert_eq!(
        ::std::mem::align_of::<buffer_data>(),
        8usize,
        concat!("Alignment of ", stringify!(buffer_data))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(buffer_data),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).buf) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(buffer_data),
            "::",
            stringify!(buf)
        )
    );
}

#[link(name = "teeverifier")]
extern "C" {
    pub fn tee_verify_report(
        data_buf: *mut buffer_data,
        nonce: *mut buffer_data,
        type_: ::std::os::raw::c_int,
        filename: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
