# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# secGear is licensed under the Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
# http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
# PURPOSE.
# See the Mulan PSL v2 for more details.

# 规则详细信息请使用 secharden help <规则编号> 命令查看
# 全栈完整性
## int.01 启用内核模块签名
int.01:
## int.02 启用DIM动态度量内核
int.02:
# 内核加固
## kern.01 开启BPF加固功能
kern.01:
## kern.02 启用内核ASLR
kern.02:
## kern.03 确保内核触发错误后直接退出
kern.03:
# 登录认证
## login.01 禁止空口令登录
login.01:
## login.02 禁止使用PermitUserEnvironment
login.02:
## login.03 禁用root用户通过SSH登录
login.03:
## login.04 禁用SSH的TCP转发功能
login.04:
## login.05 禁止使用X11 Forwarding
login.05:
## login.06 禁止使用SysRq键
login.06:
## login.07 避免开启tcp_timestamps
login.07:
## login.08 设置最大认证次数
login.08:
# 网络保护
## net.01 禁止ICMP重定向报文
net.01:
## net.02 禁止系统响应ICMP广播报文
net.02:
## net.03 禁止IP转发
net.03:
## net.04 禁止使用ARP代理
net.04:
## net.05 禁止报文源路由
net.05:
## net.06 丢弃伪造的ICMP报文
net.06:
## net.07 启用防火墙服务
net.07:
## net.08 启用反向地址过滤
net.08:
## net.09 启用TCP-SYN cookie
net.09:
# 权限最小化
## priv.01 最小化文件权限
priv.01:
## priv.02 启用链接文件保护
priv.02:
# 启用安全服务
## serv.01 启用rsyslog服务
serv.01:
## serv.02 Selinux启用enforce模式
serv.02:
# 限制高危系统功能
## sys.01 配置dmesg访问权限
sys.01:
## sys.02 禁止开启kexec功能
sys.02:
## sys.03 限制内核符号读取权限
sys.03:
## sys.04 限制ptrace范围
sys.04:
## sys.05 禁用不常见网络服务
sys.05:
