[workspace]
resolver = "2"
members = [
    "agent",
    "attester",
    "token"
]

[workspace.dependencies]
anyhow = "1.0"
config = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"
base64-url = "3.0.0"
async-trait = "0.1.78"
tokio = "1.0"
log = "0.4.14"
env_logger = "0.9"
safer-ffi = "0.1.8"
futures = "0.3.30"
reqwest = { version = "0.12" }
jsonwebtoken = "9.3.0"

verifier = {path = "../attestation-service/verifier", default-features = false}
