ARG BASE_IMAGE
ARG SECGEAR_REPO_URL

FROM ${BASE_IMAGE} as attestation-service-builder

ARG SECGEAR_REPO_URL
WORKDIR /app
COPY --from=data . .

RUN dnf install -y perl git rust cargo rust-packaging kunpengsecl-attester && \
    cd attestation-service && \
    cargo build --release

# 第二阶段：运行时
FROM ${BASE_IMAGE} 
ARG SECGEAR_REPO_URL

RUN dnf install -y python3-pip openssl shadow kunpengsecl-attester && \
    pip3 config set global.index-url https://mirrors.huaweicloud.com/repository/pypi/simple && \
    pip3 install supervisor pyjwt requests flask gunicorn gunicorn[gevent] toml && \
    mkdir -p /opt/attestation/attestation-service/verifier/virtcca && \
    mkdir -p /etc/attestation/attestation-service/resource/policy/oeas && \
    mkdir -p /opt/attestation/attestation-service/policy && \
    mkdir -p /opt/attestation/attestation-service/token && \
    mkdir -p /opt/attestation/conf && \
    mkdir -p /opt/attestation/logs && \
    dnf clean all && \
    rm -rf /var/cache/yum/* && \
    rm -rf /root/.cache/pip/*

# 复制构建产物
WORKDIR /opt/attestation
COPY ./conf ./conf
COPY --from=attestation-service-builder /app/attestation-service/target/release/attestation-service /usr/local/bin
COPY --from=attestation-service-builder /app/attestation-service/policy/src/opa/*.rego /opt/attestation/attestation-service/policy/
COPY --from=attestation-service-builder /app/attestation-types/src/resource/policy/opa/*.rego /opt/attestation/attestation-service/resource/policy/oeas/

RUN mv ./conf/Huawei* /opt/attestation/attestation-service/verifier/virtcca/ && \
    mv ./conf/attestation-service.conf /opt/attestation/attestation-service/ && \
    groupadd -g 1000 oeas && \
    useradd -m -u 1000 -g 1000 oeas && \
    chmod +x /opt/attestation/conf/start.sh && \
    chmod +x /usr/local/bin/attestation-service && \
    yes | cp -r  /opt/attestation /etc && \
    chown -R oeas:oeas /opt/attestation  && \
    chown -R oeas:oeas /etc/attestation

# 最终切换用户
USER oeas
WORKDIR /etc/attestation

ENTRYPOINT ["/opt/attestation/conf/start.sh"]
