ARG BASE_IMAGE
FROM ${BASE_IMAGE} 

WORKDIR /opt/attestation

RUN dnf install -y python3-pip openssl shadow kunpengsecl-attester \
    secGear-as virtCCA_sdk virtCCA_sdk-devel itrustee_sdk itrustee_sdk-devel \
    rust cargo rust-packaging kunpengsecl-attester && \
    pip3 config set global.index-url https://mirrors.huaweicloud.com/repository/pypi/simple && \
    pip3 install supervisor pyjwt requests flask gunicorn gunicorn[gevent] toml && \
    cp -r /etc/attestation/* ./ && \
    mkdir -p /opt/attestation/attestation-service/verifier/virtcca && \
    mkdir -p /opt/attestation/attestation-service/token && \
    mkdir -p /opt/attestation/conf && \
    mkdir -p /opt/attestation/logs && \
    dnf clean all && \
    rm -rf /var/cache/yum/* && \
    rm -rf /root/.cache/pip/*

COPY ./conf ./conf

RUN mv ./conf/Huawei* /opt/attestation/attestation-service/verifier/virtcca/ && \
    groupadd -g 1000 oeas && \
    useradd -m -u 1000 -g 1000 oeas && \
    chmod +x /opt/attestation/start.sh && \
    chmod +x /usr/local/bin/attestation-service && \
    yes | cp -r  /opt/attestation /etc && \
    chown -R oeas:oeas /opt/attestation  && \
    chown -R oeas:oeas /etc/attestation

# 最终切换用户
USER oeas
WORKDIR /etc/attestation

ENTRYPOINT ["/opt/attestation/start.sh"]