[package]
name = "attestation-service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
serde.workspace = true
hex.workspace = true
serde_json.workspace = true

actix-web.workspace = true
actix-web-httpauth.workspace = true
env_logger.workspace = true
tokio.workspace = true
log.workspace = true
base64-url.workspace = true
base64.workspace = true

verifier = { path = "../verifier" }
token_signer = { path = "../token" }
reference = { path = "../reference" }
policy = { path = "../policy" }
resource = { path = "../resource" }
strum.workspace = true
thiserror.workspace = true
clap.workspace = true
uuid.workspace = true
rand.workspace = true
scc.workspace = true
attestation-types.workspace = true
openssl.workspace = true
futures.workspace = true

[features]
