[package]
name = "attestation-agent"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aa-test"

[[bin]]
name = "generate-headers"
required-features = ["headers"]

[lib]
name = "attestation_agent"
crate-type = ["lib", "cdylib"]

[features]
no_as = []
itrustee-attester = ["attester/itrustee-attester"]
virtcca-attester = ["attester/virtcca-attester"]
all-attester = ["attester/itrustee-attester", "attester/virtcca-attester"]
itrustee-verifier = ["verifier/itrustee-verifier"]
virtcca-verifier = ["verifier/virtcca-verifier"]
all-verifier = ["verifier/itrustee-verifier", "verifier/virtcca-verifier"]
headers = ["safer-ffi/headers"]

[dependencies]
anyhow.workspace = true
config.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
log.workspace = true
env_logger.workspace = true
safer-ffi.workspace = true
futures.workspace = true
reqwest = { workspace = true, features = ["json"] }
base64-url.workspace = true
thiserror.workspace = true
actix-web.workspace = true
clap.workspace = true

attester = { path = "../attester" }
token = { path = "../token" }
verifier = { workspace = true, optional = true }
