[package]
name = "attestation-agent"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aa-test"

[[bin]]
name = "generate-headers"
required-features = ["headers"]

[lib]
name = "attestation_agent"
crate-type = ["lib", "cdylib"]

[features]
no_as = [ "verifier" ]
with_as = []
all = ["itrustee", "virtcca"]
itrustee = ["attester/itrustee-attester", "verifier/itrustee-verifier"]
virtcca = ["attester/virtcca-attester", "verifier/virtcca-verifier"]
headers = ["safer-ffi/headers"]

[dependencies]
anyhow.workspace = true
config.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
log.workspace = true
env_logger.workspace = true
safer-ffi.workspace = true
futures.workspace = true

attester = { path = "../attester" }
verifier = { workspace = true, optional = true }
