[package]
name = "attestation-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.85"
clap = { version = "4.5.24", features = ["derive", "std"] }
reqwest = { version = "0.12.5", features = ["blocking", "cookies", "json"] }
thiserror = "2.0.10"
http = "1.2.0"
tokio = { version = "1.43.0", features = ["full"] }
attestation-types = { path = "../attestation-types" }
